# Generated by Django 5.1.5 on 2025-03-05 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockDay',
            fields=[
                ('stock_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('stock_name', models.CharField(max_length=20)),
                ('data_json', models.JSONField()),
                ('ma5', models.JSONField()),
                ('ma10', models.JSONField()),
                ('ma20', models.JSONField()),
                ('ma60', models.JSONField()),
                ('date_nums', models.JSONField()),
                ('last_updated', models.DateTimeField()),
            ],
        ),
    ]
