# Generated by Django 5.1.5 on 2025-03-05 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockCodes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockday',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
