# Generated by Django 5.1.5 on 2025-03-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockCodes', '0002_alter_stockday_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockday',
            name='img_64',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockday',
            name='stock_code',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
