# Generated by Django 5.1.5 on 2025-03-05 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockCodes', '0003_stockday_img_64_alter_stockday_stock_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockday',
            name='stock_name',
        ),
    ]
