# Generated by Django 5.1.5 on 2025-03-05 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockCodes', '0004_remove_stockday_stock_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockday',
            name='data_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockday',
            name='date_nums',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockday',
            name='ma10',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockday',
            name='ma20',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockday',
            name='ma5',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockday',
            name='ma60',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
