# Generated by Django 5.1.5 on 2025-02-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bwibbu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bwibbu',
            name='DividendYield',
        ),
        migrations.RemoveField(
            model_name='bwibbu',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='bwibbu',
            name='PBratio',
        ),
        migrations.RemoveField(
            model_name='bwibbu',
            name='PEratio',
        ),
        migrations.RemoveField(
            model_name='bwibbu',
            name='id',
        ),
        migrations.AddField(
            model_name='bwibbu',
            name='dividend_yield',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bwibbu',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bwibbu',
            name='pb_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bwibbu',
            name='pe_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bwibbu',
            name='stock_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='bwibbu',
            table='bwibbu_stock_data',
        ),
        migrations.AddField(
            model_name='bwibbu',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
